// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


import Navbar from './navbar';
import Footer from './footer';
import React from 'react';

export default function Layout({ children }: { children: React.ReactNode }) {
    return (
        // Kontainer utama untuk layout, membuatnya menjadi flex column
        // dan memastikan tinggi minimalnya adalah 100% dari viewport
        <div className="flex flex-col min-h-screen">
            <Navbar />
            {/* Konten utama yang akan mengisi sisa ruang yang tersedia */}
            <main className="flex-grow">
                {children}
            </main>
            <Footer />
        </div>
    );
}