import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
    return (
        <> {/* Ganti dengan fragmen React jika Layout dihapus */}
            <Head>
                <title>Beranda | Next.js Course</title>
                <meta name='title' content='Home Page' />
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen flex-col items-center justify-center p-24">
                <h1 className="text-4xl font-bold text-blue-600">Welcome to the course!</h1>
                <Image
                    className="my-8"
                    src="/next.svg"
                    alt="Next.js logo"
                    width={180}
                    height={37}
                    priority
                />
                <p className="mt-4 text-lg text-gray-700">
                    This is an example page using Tailwind CSS.
                </p>
            </main>
        </> // Ganti dengan fragmen React jika Layout dihapus
    );
}